// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_client.sql

package store

import (
	"context"
)

const createDownloadClient = `-- name: CreateDownloadClient :one
INSERT INTO download_client (
    name, implementation, config_contract, protocol, priority, enable, fields, tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, implementation, config_contract, protocol, priority, enable, fields, tags, created_at, updated_at
`

type CreateDownloadClientParams struct {
	Name           string
	Implementation string
	ConfigContract string
	Protocol       string
	Priority       int32
	Enable         bool
	Fields         []byte
	Tags           []byte
}

func (q *Queries) CreateDownloadClient(ctx context.Context, arg CreateDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRow(ctx, createDownloadClient,
		arg.Name,
		arg.Implementation,
		arg.ConfigContract,
		arg.Protocol,
		arg.Priority,
		arg.Enable,
		arg.Fields,
		arg.Tags,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Implementation,
		&i.ConfigContract,
		&i.Protocol,
		&i.Priority,
		&i.Enable,
		&i.Fields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDownloadClient = `-- name: DeleteDownloadClient :exec
DELETE FROM download_client WHERE id = $1
`

func (q *Queries) DeleteDownloadClient(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDownloadClient, id)
	return err
}

const getDownloadClient = `-- name: GetDownloadClient :one
SELECT id, name, implementation, config_contract, protocol, priority, enable, fields, tags, created_at, updated_at FROM download_client WHERE id = $1
`

func (q *Queries) GetDownloadClient(ctx context.Context, id int64) (DownloadClient, error) {
	row := q.db.QueryRow(ctx, getDownloadClient, id)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Implementation,
		&i.ConfigContract,
		&i.Protocol,
		&i.Priority,
		&i.Enable,
		&i.Fields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDownloadClients = `-- name: ListDownloadClients :many
SELECT id, name, implementation, config_contract, protocol, priority, enable, fields, tags, created_at, updated_at FROM download_client ORDER BY priority, name
`

func (q *Queries) ListDownloadClients(ctx context.Context) ([]DownloadClient, error) {
	rows, err := q.db.Query(ctx, listDownloadClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadClient{}
	for rows.Next() {
		var i DownloadClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Implementation,
			&i.ConfigContract,
			&i.Protocol,
			&i.Priority,
			&i.Enable,
			&i.Fields,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadClient = `-- name: UpdateDownloadClient :one
UPDATE download_client SET
    name = $2,
    implementation = $3,
    config_contract = $4,
    protocol = $5,
    priority = $6,
    enable = $7,
    fields = $8,
    tags = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, name, implementation, config_contract, protocol, priority, enable, fields, tags, created_at, updated_at
`

type UpdateDownloadClientParams struct {
	ID             int64
	Name           string
	Implementation string
	ConfigContract string
	Protocol       string
	Priority       int32
	Enable         bool
	Fields         []byte
	Tags           []byte
}

func (q *Queries) UpdateDownloadClient(ctx context.Context, arg UpdateDownloadClientParams) (DownloadClient, error) {
	row := q.db.QueryRow(ctx, updateDownloadClient,
		arg.ID,
		arg.Name,
		arg.Implementation,
		arg.ConfigContract,
		arg.Protocol,
		arg.Priority,
		arg.Enable,
		arg.Fields,
		arg.Tags,
	)
	var i DownloadClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Implementation,
		&i.ConfigContract,
		&i.Protocol,
		&i.Priority,
		&i.Enable,
		&i.Fields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
