// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHistory = `-- name: CreateHistory :one
INSERT INTO history (movie_id, event_type, source_title, quality, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, movie_id, event_type, source_title, quality, data, date
`

type CreateHistoryParams struct {
	MovieID     pgtype.Int8
	EventType   string
	SourceTitle string
	Quality     string
	Data        []byte
}

func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) (History, error) {
	row := q.db.QueryRow(ctx, createHistory,
		arg.MovieID,
		arg.EventType,
		arg.SourceTitle,
		arg.Quality,
		arg.Data,
	)
	var i History
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.EventType,
		&i.SourceTitle,
		&i.Quality,
		&i.Data,
		&i.Date,
	)
	return i, err
}

const getMovieFile = `-- name: GetMovieFile :one
SELECT id, movie_id, relative_path, path, size, quality, date_added FROM movie_file WHERE movie_id = $1
`

func (q *Queries) GetMovieFile(ctx context.Context, movieID int64) (MovieFile, error) {
	row := q.db.QueryRow(ctx, getMovieFile, movieID)
	var i MovieFile
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RelativePath,
		&i.Path,
		&i.Size,
		&i.Quality,
		&i.DateAdded,
	)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT id, movie_id, event_type, source_title, quality, data, date FROM history ORDER BY date DESC LIMIT $1
`

func (q *Queries) ListHistory(ctx context.Context, limit int32) ([]History, error) {
	rows, err := q.db.Query(ctx, listHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.EventType,
			&i.SourceTitle,
			&i.Quality,
			&i.Data,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMovieImported = `-- name: SetMovieImported :exec
UPDATE movie SET has_file = TRUE, path = $2, updated_at = now() WHERE id = $1
`

type SetMovieImportedParams struct {
	ID   int64
	Path pgtype.Text
}

func (q *Queries) SetMovieImported(ctx context.Context, arg SetMovieImportedParams) error {
	_, err := q.db.Exec(ctx, setMovieImported, arg.ID, arg.Path)
	return err
}

const upsertMovieFile = `-- name: UpsertMovieFile :one
INSERT INTO movie_file (movie_id, relative_path, path, size, quality)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (movie_id) DO UPDATE SET
    relative_path = EXCLUDED.relative_path,
    path = EXCLUDED.path,
    size = EXCLUDED.size,
    quality = EXCLUDED.quality,
    date_added = now()
RETURNING id, movie_id, relative_path, path, size, quality, date_added
`

type UpsertMovieFileParams struct {
	MovieID      int64
	RelativePath string
	Path         string
	Size         int64
	Quality      string
}

func (q *Queries) UpsertMovieFile(ctx context.Context, arg UpsertMovieFileParams) (MovieFile, error) {
	row := q.db.QueryRow(ctx, upsertMovieFile,
		arg.MovieID,
		arg.RelativePath,
		arg.Path,
		arg.Size,
		arg.Quality,
	)
	var i MovieFile
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.RelativePath,
		&i.Path,
		&i.Size,
		&i.Quality,
		&i.DateAdded,
	)
	return i, err
}
