// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: indexer.sql

package store

import (
	"context"
)

const createIndexer = `-- name: CreateIndexer :one
INSERT INTO indexer (
    name, implementation, config_contract, protocol, priority,
    enable_rss, enable_automatic_search, enable_interactive_search, fields, tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, name, implementation, config_contract, protocol, priority, enable_rss, enable_automatic_search, enable_interactive_search, fields, tags, created_at, updated_at
`

type CreateIndexerParams struct {
	Name                    string
	Implementation          string
	ConfigContract          string
	Protocol                string
	Priority                int32
	EnableRss               bool
	EnableAutomaticSearch   bool
	EnableInteractiveSearch bool
	Fields                  []byte
	Tags                    []byte
}

func (q *Queries) CreateIndexer(ctx context.Context, arg CreateIndexerParams) (Indexer, error) {
	row := q.db.QueryRow(ctx, createIndexer,
		arg.Name,
		arg.Implementation,
		arg.ConfigContract,
		arg.Protocol,
		arg.Priority,
		arg.EnableRss,
		arg.EnableAutomaticSearch,
		arg.EnableInteractiveSearch,
		arg.Fields,
		arg.Tags,
	)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Implementation,
		&i.ConfigContract,
		&i.Protocol,
		&i.Priority,
		&i.EnableRss,
		&i.EnableAutomaticSearch,
		&i.EnableInteractiveSearch,
		&i.Fields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIndexer = `-- name: DeleteIndexer :exec
DELETE FROM indexer WHERE id = $1
`

func (q *Queries) DeleteIndexer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIndexer, id)
	return err
}

const getIndexer = `-- name: GetIndexer :one
SELECT id, name, implementation, config_contract, protocol, priority, enable_rss, enable_automatic_search, enable_interactive_search, fields, tags, created_at, updated_at FROM indexer WHERE id = $1
`

func (q *Queries) GetIndexer(ctx context.Context, id int64) (Indexer, error) {
	row := q.db.QueryRow(ctx, getIndexer, id)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Implementation,
		&i.ConfigContract,
		&i.Protocol,
		&i.Priority,
		&i.EnableRss,
		&i.EnableAutomaticSearch,
		&i.EnableInteractiveSearch,
		&i.Fields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndexers = `-- name: ListIndexers :many
SELECT id, name, implementation, config_contract, protocol, priority, enable_rss, enable_automatic_search, enable_interactive_search, fields, tags, created_at, updated_at FROM indexer ORDER BY name
`

func (q *Queries) ListIndexers(ctx context.Context) ([]Indexer, error) {
	rows, err := q.db.Query(ctx, listIndexers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indexer{}
	for rows.Next() {
		var i Indexer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Implementation,
			&i.ConfigContract,
			&i.Protocol,
			&i.Priority,
			&i.EnableRss,
			&i.EnableAutomaticSearch,
			&i.EnableInteractiveSearch,
			&i.Fields,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndexer = `-- name: UpdateIndexer :one
UPDATE indexer SET
    name = $2,
    implementation = $3,
    config_contract = $4,
    protocol = $5,
    priority = $6,
    enable_rss = $7,
    enable_automatic_search = $8,
    enable_interactive_search = $9,
    fields = $10,
    tags = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, name, implementation, config_contract, protocol, priority, enable_rss, enable_automatic_search, enable_interactive_search, fields, tags, created_at, updated_at
`

type UpdateIndexerParams struct {
	ID                      int64
	Name                    string
	Implementation          string
	ConfigContract          string
	Protocol                string
	Priority                int32
	EnableRss               bool
	EnableAutomaticSearch   bool
	EnableInteractiveSearch bool
	Fields                  []byte
	Tags                    []byte
}

func (q *Queries) UpdateIndexer(ctx context.Context, arg UpdateIndexerParams) (Indexer, error) {
	row := q.db.QueryRow(ctx, updateIndexer,
		arg.ID,
		arg.Name,
		arg.Implementation,
		arg.ConfigContract,
		arg.Protocol,
		arg.Priority,
		arg.EnableRss,
		arg.EnableAutomaticSearch,
		arg.EnableInteractiveSearch,
		arg.Fields,
		arg.Tags,
	)
	var i Indexer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Implementation,
		&i.ConfigContract,
		&i.Protocol,
		&i.Priority,
		&i.EnableRss,
		&i.EnableAutomaticSearch,
		&i.EnableInteractiveSearch,
		&i.Fields,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
