// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DownloadClient struct {
	ID             int64
	Name           string
	Implementation string
	ConfigContract string
	Protocol       string
	Priority       int32
	Enable         bool
	Fields         []byte
	Tags           []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type History struct {
	ID          int64
	MovieID     pgtype.Int8
	EventType   string
	SourceTitle string
	Quality     string
	Data        []byte
	Date        pgtype.Timestamptz
}

type Indexer struct {
	ID                      int64
	Name                    string
	Implementation          string
	ConfigContract          string
	Protocol                string
	Priority                int32
	EnableRss               bool
	EnableAutomaticSearch   bool
	EnableInteractiveSearch bool
	Fields                  []byte
	Tags                    []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type Movie struct {
	ID               int64
	TmdbID           int64
	Title            string
	Year             pgtype.Int4
	Monitored        bool
	AddedAt          pgtype.Timestamptz
	TitleSlug        pgtype.Text
	SortTitle        pgtype.Text
	Overview         pgtype.Text
	Status           pgtype.Text
	Runtime          int32
	HasFile          bool
	ImdbID           pgtype.Text
	Path             pgtype.Text
	RootFolderPath   pgtype.Text
	Images           []byte
	QualityProfileID pgtype.Int8
	UpdatedAt        pgtype.Timestamptz
}

type MovieFile struct {
	ID           int64
	MovieID      int64
	RelativePath string
	Path         string
	Size         int64
	Quality      string
	DateAdded    pgtype.Timestamptz
}

type QualityProfile struct {
	ID              int64
	Name            string
	UpgradeAllowed  bool
	CutoffQualityID pgtype.Int4
	Items           []byte
	CreatedAt       pgtype.Timestamptz
}

type RootFolder struct {
	ID        int64
	Path      string
	CreatedAt pgtype.Timestamptz
}

type Tag struct {
	ID        int64
	Label     string
	CreatedAt pgtype.Timestamptz
}
