// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movie.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movie (
    tmdb_id, title, year, monitored, title_slug, sort_title, overview,
    status, runtime, imdb_id, path, root_folder_path, images, quality_profile_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, tmdb_id, title, year, monitored, added_at, title_slug, sort_title, overview, status, runtime, has_file, imdb_id, path, root_folder_path, images, quality_profile_id, updated_at
`

type CreateMovieParams struct {
	TmdbID           int64
	Title            string
	Year             pgtype.Int4
	Monitored        bool
	TitleSlug        pgtype.Text
	SortTitle        pgtype.Text
	Overview         pgtype.Text
	Status           pgtype.Text
	Runtime          int32
	ImdbID           pgtype.Text
	Path             pgtype.Text
	RootFolderPath   pgtype.Text
	Images           []byte
	QualityProfileID pgtype.Int8
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.TmdbID,
		arg.Title,
		arg.Year,
		arg.Monitored,
		arg.TitleSlug,
		arg.SortTitle,
		arg.Overview,
		arg.Status,
		arg.Runtime,
		arg.ImdbID,
		arg.Path,
		arg.RootFolderPath,
		arg.Images,
		arg.QualityProfileID,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.Monitored,
		&i.AddedAt,
		&i.TitleSlug,
		&i.SortTitle,
		&i.Overview,
		&i.Status,
		&i.Runtime,
		&i.HasFile,
		&i.ImdbID,
		&i.Path,
		&i.RootFolderPath,
		&i.Images,
		&i.QualityProfileID,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovie = `-- name: GetMovie :one
SELECT id, tmdb_id, title, year, monitored, added_at, title_slug, sort_title, overview, status, runtime, has_file, imdb_id, path, root_folder_path, images, quality_profile_id, updated_at FROM movie WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.Monitored,
		&i.AddedAt,
		&i.TitleSlug,
		&i.SortTitle,
		&i.Overview,
		&i.Status,
		&i.Runtime,
		&i.HasFile,
		&i.ImdbID,
		&i.Path,
		&i.RootFolderPath,
		&i.Images,
		&i.QualityProfileID,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovieByTMDB = `-- name: GetMovieByTMDB :one
SELECT id, tmdb_id, title, year, monitored, added_at, title_slug, sort_title, overview, status, runtime, has_file, imdb_id, path, root_folder_path, images, quality_profile_id, updated_at FROM movie WHERE tmdb_id = $1
`

func (q *Queries) GetMovieByTMDB(ctx context.Context, tmdbID int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByTMDB, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.Monitored,
		&i.AddedAt,
		&i.TitleSlug,
		&i.SortTitle,
		&i.Overview,
		&i.Status,
		&i.Runtime,
		&i.HasFile,
		&i.ImdbID,
		&i.Path,
		&i.RootFolderPath,
		&i.Images,
		&i.QualityProfileID,
		&i.UpdatedAt,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, tmdb_id, title, year, monitored, added_at, title_slug, sort_title, overview, status, runtime, has_file, imdb_id, path, root_folder_path, images, quality_profile_id, updated_at FROM movie ORDER BY sort_title NULLS LAST, title
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.Monitored,
			&i.AddedAt,
			&i.TitleSlug,
			&i.SortTitle,
			&i.Overview,
			&i.Status,
			&i.Runtime,
			&i.HasFile,
			&i.ImdbID,
			&i.Path,
			&i.RootFolderPath,
			&i.Images,
			&i.QualityProfileID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
