// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movie.sql

package store

import (
	"context"
)

const getMovie = `-- name: GetMovie :one
SELECT id, tmdb_id, title, year, monitored, added_at, title_slug, sort_title, overview, status, runtime, has_file, imdb_id, path, root_folder_path, images, quality_profile_id, updated_at FROM movie WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.Monitored,
		&i.AddedAt,
		&i.TitleSlug,
		&i.SortTitle,
		&i.Overview,
		&i.Status,
		&i.Runtime,
		&i.HasFile,
		&i.ImdbID,
		&i.Path,
		&i.RootFolderPath,
		&i.Images,
		&i.QualityProfileID,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovieByTMDB = `-- name: GetMovieByTMDB :one
SELECT id, tmdb_id, title, year, monitored, added_at, title_slug, sort_title, overview, status, runtime, has_file, imdb_id, path, root_folder_path, images, quality_profile_id, updated_at FROM movie WHERE tmdb_id = $1
`

func (q *Queries) GetMovieByTMDB(ctx context.Context, tmdbID int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByTMDB, tmdbID)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.Monitored,
		&i.AddedAt,
		&i.TitleSlug,
		&i.SortTitle,
		&i.Overview,
		&i.Status,
		&i.Runtime,
		&i.HasFile,
		&i.ImdbID,
		&i.Path,
		&i.RootFolderPath,
		&i.Images,
		&i.QualityProfileID,
		&i.UpdatedAt,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, tmdb_id, title, year, monitored, added_at, title_slug, sort_title, overview, status, runtime, has_file, imdb_id, path, root_folder_path, images, quality_profile_id, updated_at FROM movie ORDER BY sort_title NULLS LAST, title
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.Monitored,
			&i.AddedAt,
			&i.TitleSlug,
			&i.SortTitle,
			&i.Overview,
			&i.Status,
			&i.Runtime,
			&i.HasFile,
			&i.ImdbID,
			&i.Path,
			&i.RootFolderPath,
			&i.Images,
			&i.QualityProfileID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
