// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quality_profile.sql

package store

import (
	"context"
)

const getQualityProfile = `-- name: GetQualityProfile :one
SELECT id, name, upgrade_allowed, cutoff_quality_id, items, created_at FROM quality_profile WHERE id = $1
`

func (q *Queries) GetQualityProfile(ctx context.Context, id int64) (QualityProfile, error) {
	row := q.db.QueryRow(ctx, getQualityProfile, id)
	var i QualityProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UpgradeAllowed,
		&i.CutoffQualityID,
		&i.Items,
		&i.CreatedAt,
	)
	return i, err
}

const listQualityProfiles = `-- name: ListQualityProfiles :many
SELECT id, name, upgrade_allowed, cutoff_quality_id, items, created_at FROM quality_profile ORDER BY id
`

func (q *Queries) ListQualityProfiles(ctx context.Context) ([]QualityProfile, error) {
	rows, err := q.db.Query(ctx, listQualityProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityProfile{}
	for rows.Next() {
		var i QualityProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UpgradeAllowed,
			&i.CutoffQualityID,
			&i.Items,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
