// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: root_folder.sql

package store

import (
	"context"
)

const createRootFolder = `-- name: CreateRootFolder :one
INSERT INTO root_folder (path) VALUES ($1)
RETURNING id, path, created_at
`

func (q *Queries) CreateRootFolder(ctx context.Context, path string) (RootFolder, error) {
	row := q.db.QueryRow(ctx, createRootFolder, path)
	var i RootFolder
	err := row.Scan(&i.ID, &i.Path, &i.CreatedAt)
	return i, err
}

const deleteRootFolder = `-- name: DeleteRootFolder :exec
DELETE FROM root_folder WHERE id = $1
`

func (q *Queries) DeleteRootFolder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRootFolder, id)
	return err
}

const getRootFolder = `-- name: GetRootFolder :one
SELECT id, path, created_at FROM root_folder WHERE id = $1
`

func (q *Queries) GetRootFolder(ctx context.Context, id int64) (RootFolder, error) {
	row := q.db.QueryRow(ctx, getRootFolder, id)
	var i RootFolder
	err := row.Scan(&i.ID, &i.Path, &i.CreatedAt)
	return i, err
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, path, created_at FROM root_folder ORDER BY path
`

func (q *Queries) ListRootFolders(ctx context.Context) ([]RootFolder, error) {
	rows, err := q.db.Query(ctx, listRootFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RootFolder{}
	for rows.Next() {
		var i RootFolder
		if err := rows.Scan(&i.ID, &i.Path, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
