// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package store

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tag (label) VALUES ($1)
RETURNING id, label, created_at
`

func (q *Queries) CreateTag(ctx context.Context, label string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, label)
	var i Tag
	err := row.Scan(&i.ID, &i.Label, &i.CreatedAt)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tag WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, label, created_at FROM tag WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Label, &i.CreatedAt)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, label, created_at FROM tag ORDER BY label
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Label, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
